# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171029_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='user',
        ),
    ]
